print('l' in 'hello, world')
print('ll' in 'hello, world')
print('你好' in 'hello, world')
print('wor' in 'hello, world')
print('abc' not in 'hello, world')
print('你好' not in 'hello, world')
print('llo' not in 'hello, world')