print("0 是 ", bool(0))
print("-2 是 ", bool(-2))
print("5 是 ", bool(5))
print("1 + 5j 是 ", bool(1+5j))
print("0 + 0j 是 ", bool(0+0j))
print("0.0 是 ", bool(0.0))
print("2.3 是 ", bool(2.3))
print('"" 是 ', bool(""))
print('"hello" 是 ', bool("hello"))