greeting = "hello, world"
print(greeting[0])
print(greeting[1])
print(greeting[2])
print(greeting[3])
print(greeting[4])
print(greeting[-1])
print(greeting[-2])
print(greeting[-3])
print(greeting[-4])
