num = int(input("請輸入一個整數："))
print(F"  你輸入的是：{num:10d}")
print(F"在數字前補 0：{num:010d}")
print(F"讓數字向左對齊：{num:<10d}")
print(F" 2 進位是：{num:10b}")
print(F" 8 進位是：{num:10o}")
print(F"16 進位是：{num:10x}")
print(F" 2 進位是：{num:#10b}")
print(F" 8 進位是：{num:#10o}")
print(F"16 進位是：{num:#10X}")
